# Azure pipeline for Terraform AKS module

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imagename: terraform-azurerm-aks:$(build.buildId)
  terraformversion: 0.12.10

steps:
- script: docker build --build-arg BUILD_TERRAFORM_VERSION=${terraformVersion} --build-arg BUILD_ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID --build-arg BUILD_ARM_CLIENT_ID=$ARM_CLIENT_ID --build-arg BUILD_ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET --build-arg BUILD_ARM_TENANT_ID=$ARM_TENANT_ID -t ${imageName} .
  displayName: 'docker build'

- script: docker run ${imageName} rake full
  displayName: 'docker run'